package com.dynatrace.sample.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_java.proto

public interface TechnologyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dynatrace.sample.proto.Technology)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string tech = 1;</code>
   */
  java.lang.String getTech();
  /**
   * <code>optional string tech = 1;</code>
   */
  com.google.protobuf.ByteString
      getTechBytes();
}
